version: "3.2"

services:
  fail2ban:
    image: novice/f2b:latest
    container_name: fail2ban
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - "/var/log:/var/log:ro"
    env_file:
      - "./f2b.env"
    restart: always